all:
  vars:
    users:
    - username: foo
      name: Foo Barrington
      groups: ['wheel','systemd-journal']
      uid: 1001
      home: /local/home/foo
  hosts:
    linux1:
      ansible_host: ec2-user@ec2-3-122-114-204.eu-central-1.compute.amazonaws.com
      ansible_user: ec2-user
      ansible_ssh_private_key_file: ansible.pem
